spring:
  profiles:
    active: test
  application:
    name: discodeit

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    org.hibernate.sql: debug
    root: info

management:
  endpoints:
    web:
      exposure:
        include:
          - "health"
          - "info"
          - "metrics"
          - "loggers"

  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: Discodeit
    version: 1.7.0
    java-version: 17
    spring-boot-version: 3.4.0
  datasource:
    url: ${spring.datasource.url}
    driver-class-name: ${spring.datasource.driver-class-name}
  jpa:
    ddl-auto: ${spring.jpa.hibernate.ddl-auto}
  storage:
    type: ${discodeit.storage.type}
    path: ${discodeit.storage.path}
  multipart:
    max-file-size: ${spring.servlet.multipart.max-file-size}
    max-request-size: ${spring.servlet.multipart.max-request-size}


springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8


