CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE IF NOT EXISTS binary_contents(
    id UUID PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    file_name VARCHAR(255) NOT NULL ,
    size BIGINT NOT NULL ,
    content_type VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS users(
    id UUID PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL ,
    password VARCHAR(60) NOT NULL ,
    profile_id UUID REFERENCES binary_contents(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS channels(
    id UUID PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL ,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL ,
    name VARCHAR(100),
    description VARCHAR(500),
    type VARCHAR(10) NOT NULL CHECK ( type IN ('PUBLIC','PRIVATE'))
);

CREATE TABLE IF NOT EXISTS messages(
    id UUID PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL ,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    content TEXT,
    channel_id UUID NOT NULL REFERENCES channels(id) ON DELETE CASCADE ,
    author_id UUID REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS read_statuses(
    id UUID PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL ,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    user_id UUID REFERENCES users(id) ON DELETE CASCADE ,
    channel_id UUID REFERENCES channels(id) ON DELETE CASCADE ,
    last_read_at TIMESTAMPTZ NOT NULL,
    UNIQUE (user_id,channel_id)
);

CREATE TABLE IF NOT EXISTS user_statuses(
    id UUID PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL ,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE ,
    last_active_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS messages_attachments(
    message_id UUID REFERENCES users(id) ON DELETE CASCADE ,
    attachments_id UUID REFERENCES binary_contents(id) ON DELETE CASCADE
);





