FROM nginx:stable-alpine

COPY default.conf /etc/nginx/conf.d/default.conf
COPY ../1-sprint-mission/src/main/resources/static /usr/share/nginx/html/
COPY ../1-sprint-mission/src/main/resources/templates /usr/share/nginx/html/
